// console.log(Rahul)  And this this error handling bcz rahul is not define
// we can solve this problem by using try catch function
try{
  console.log(rahul)
}
catch (error) {
  console.log("HERE IS OCCUR NEW ERROR")
}

// Rahul is not define in the code  it is running succesfully by the help of try catch method

setTimeout(() => {
  console.log("wifi hacking.... ")
}, 1000);

setTimeout(() => {
  console.log("Rahul facebook id details  fetching.........")
}, 5000);

setTimeout(() => {
  console.log("xxxxxxx92 is Rahul number ")
}, 8000);

// practice second
try{
  let a = 0;
  console.log(program)// this is an error there will be catch and finally will be run
  console.log("program run succe3ssfully ")
}
catch{

console.log("there is an Errror")

}
finally{
  console.log(" i am good boy")
  // close the file
  // exit the file
  // exit loop
  // exit to log 
}